### ISSUE TITLE
No kramdown bug, just wrong syntax used

### ISSUE THREAD

**Issue by gettalong** [tomjohnson1492/kramdowntest#1]
Hi,

I don't think that there is a bug but that you are thinking of a different Markdown syntax. Please read the [kramdown syntax guide regarding lists](http://kramdown.gettalong.org/syntax.html#lists) for detailed information.

The gist is that the indentation for the list contents is determined by the column number of the first non-space character after the list item marker.

Examples (edit: I replaced the leading spaces with underscores so it looks correct):

* `*_some text` -> 2 spaces indentation
* `*___some text` -> 4 spaces indentation
* `1._some text` -> 3 spaces indentation

So if you just line up the contents of the list item with the natural indentation, it will work.

As for your examples:

* The kramdown parser does **not** support fenced code blocks with backticks. You have to use the GFM parser if you want that functionality.

* The indentation for the "Kramdown tildes" examples is wrong and therefore it doesn't work.

Your example:

~~~
## Kramdown tildes

1. Do step 1.
2. Now do this:
    
    ~~~ ruby
    def print_hi(name)
      puts "Hi, #{name}"
    end
    print_hi('Tom')
    #=> prints 'Hi, Tom' to STDOUT.
    ~~~
~~~

As you can see, the tildes are indented **four** spaces although the list item indentation is only **three** spaces. Since the fenced code block syntax doesn't allow leading spaces (as other block elements like blockquotes do), the whole thing is treated as a paragraph.

In the example "Github fenced code blocks" backticks are used. However, the indentation is also wrong but since backticks are used for inline code markup, the contents is wrapped in a `<code>` tag.

I hope this clears everything up.

**Comment by geraldb** [comment]
FYI: This might help. I've updated the example with the help of Thomas Leitner - the kramdown developer. It works!

All you have to fix is your indentation e.g. use three spaces max. for your code block (for level 1) and 3+4 e.g. 7 spaces max. for your code block (for level 2) and so on. See the sample [source](http://planetjekyll.github.io/sandbox-syntax-highlighter/lists.html) and [rendered with GitHub Pages](https://github.com/planetjekyll/sandbox-syntax-highlighter/blob/gh-pages/lists.md). Cheers.

**Comment by tomjohnson1492** [comment]
Ahhh, now I see. Thanks for clarifying. Changing the indentation from 4 spaces to 3 spaces fixes it! 

Here's the problem with the Github Pages announcement. Their announcement says that you just have to change redcarpet and pygments to kramdown and rouge, but it doesn't note that the indentation syntax for code blocks must also be updated. 

I believe the Github-flavored markdown syntax for code blocks within lists requires an indentation of **4** spaces. Here are a couple of excerpts where I'm getting that:

"Blocks of code are either fenced by lines with three back-ticks ```, or are indented with four spaces." [https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

"To preserve your formatting within a list, make sure to indent non-fenced code blocks by eight spaces."
[https://help.github.com/articles/creating-and-highlighting-code-blocks/](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

So for people converting from redcarpet and pygments to kramdown and rouge, they need to also change the indentation from 4 spaces to 3, right? Or at least the spacing needs to align with the guidance you articulated above:

>The gist is that the indentation for the list contents is determined by the column number of the first non-space character after the list item marker.

**Comment by tomjohnson1492** [comment]
I updated my blog post to make it more accurate given the insight about the correct indentation. [Updating from redcarpet and Pygments to Kramdown and Rouge on Github Pages](http://idratherbewriting.com/2016/02/21/bug-with-kramdown-and-rouge-with-github-pages/)

**Comment by gettalong** [comment]
Changing the indentation from 4 to 3 spaces fixes it in your case but not in all cases! Remembering the number of spaces you used before won't do the trick in the general case.

It is better to just remember that the left margin for the content of list items is determined by the column number of the first non-space character after the list item marker.

And also note: This has **nothing to do with code blocks**! For example, if you have an indented code block inside a blockquote, you need to use the greater-than sign and **5** spaces (one so that the blockquote is recognized and four for the indented code block). However, if you use a fenced code block, than you need to only use the greater-than sign and **1** space (so that the blockquote is recognized).

As for your references: These are references for a specific implementation of Markdown but since there is **no Markdown specification** all implementations differ in certain aspects. I decided to make list indentation work differently so that many edge cases that didn't easily/correctly work in other implementations won't occur with kramdown and that the plain text still looks nice.
